routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//======= Admin =========//

#Dashboard
Route::get('admin','Admin\AdminHomeController@index')->name('admin.index');


#Admin Roles
Route::resource('admin/roles', 'Admin\AdminRoleController', ['names'=>[
    'index'=>'admin.roles.index',
    'create'=>'admin.roles.create',
    'store'=>'admin.roles.store',
    'edit'=>'admin.roles.edit'
]]);

#Admin Users
Route::resource('admin/users', 'Admin\AdminUserController', ['names'=>[
    'index'=>'admin.users.index',
    'create'=>'admin.users.create',
    'store'=>'admin.users.store',
    'edit' => 'admin.users.edit'
]]);


#Admin SiteInformation
Route::resource('admin/site-information', 'Admin\AdminSiteInformationController', ['names'=>[
    'index'=>'admin.site-information.index',
    'create'=>'admin.site-information.create',
    'store'=>'admin.site-information.store',
    'edit'=>'admin.site-information.edit'
]]);

#Admin Cities
Route::resource('admin/cities', 'Admin\AdminCityController', ['names'=>[
    'index'=>'admin.cities.index',
    'create'=>'admin.cities.create',
    'store'=>'admin.cities.store',
    'edit'=>'admin.cities.edit'
]]);

#Admin Categories
Route::resource('admin/categories', 'Admin\AdminCategoryController', ['names'=>[
    'index'=>'admin.categories.index',
    'create'=>'admin.categories.create',
    'store'=>'admin.categories.store',
    'edit'=>'admin.categories.edit'
]]);

#Admin Categories
Route::resource('admin/sub-categories', 'Admin\AdminSubCategoryController', ['names'=>[
    'index'=>'admin.sub-categories.index',
    'create'=>'admin.sub-categories.create',
    'store'=>'admin.sub-categories.store',
    'edit'=>'admin.sub-categories.edit'
]]);

#Admin Messages
Route::resource('admin/messages', 'Admin\AdminMessageController', ['names'=>[

    'index'=>'admin.messages.index',
]]);
Route::post('/delete/messages', 'Admin\AdminMessageController@deleteMessage');

#Admin Sticker

Route::get('/admin/stickers', 'Admin\AdminStickerController@index')->name('admin.stickers.index');
Route::delete('/admin/stickers/delete/{id}', 'Admin\AdminStickerController@destroy');
Route::get('/admin/stickers/{id}/edit', 'Admin\AdminStickerController@edit')->name('admin.stickers.edit');
Route::post('/admin/stickers/{id}/update', 'Admin\AdminStickerController@update');
Route::post('/admin/sticker/addImage', 'Admin\AdminStickerController@uploadImage');
Route::get('/admin/sticker/deleteImage/{id}', 'Admin\AdminStickerController@deleteImage');

Route::post('/delete/stickers', 'Admin\AdminStickerController@deleteStickers');

Route::get('/admin/stickers/status/{id}', [
  'uses' => 'Admin\AdminStickerController@status',
  'as' => 'admin.stickers.status'
]);

Route::post('/admin/stickers/image_rotate_left', ['as' => 'productImageRotateLeft', 'uses' => 'Admin\AdminStickerController@image_rotate_left']);
Route::post('/admin/stickers/image_rotate_right', ['as' => 'productImageRotateRight', 'uses' => 'Admin\AdminStickerController@image_rotate_right']);


#User Stickers
Route::get('/user/{id}/stickers', 'Admin\AdminStickerController@stickersWithUserId');
#City Stickers
Route::get('/city/{id}/stickers', 'Admin\AdminStickerController@stickersWithCityId');
#Category Stickers
Route::get('/{base_slug}/{slug}/stickers', 'Admin\AdminStickerController@stickersWithSubCategoryId');


#Admin RoleItems
Route::resource('admin/role-items', 'Admin\AdminRoleItemController', ['names'=>[
    'index'=>'admin.role-items.index',
]]);





//======== Web ========//

#Home
Route::get('/', 'HomeController@index');

Route::post('/search', 'HomeController@searchJson');

#Contact
Route::get('/contact', 'MessageController@contact');

Route::resource('message', 'MessageController', ['names'=>[
    'store'=>'site.other-pages.contact',
]]);
#About
Route::get('/about', 'HomeController@about');
#stickers
Route::get('/stickers', 'StickerController@stickers');
#Wishlist
Route::resource('/wishlist', 'WishlistController', ['except' => ['create', 'edit', 'show', 'update']]);
Route::post('/wishlist/delete/{id}', 'WishlistController@destroy');
#Add Sticker
Route::get('/sticker/add/getSubCategory/{id}', 'StickerController@subCategory');
Route::get('/sticker/add', 'StickerController@create');
Route::post('/sticker/add', 'StickerController@store');
Route::post('/sticker/addImage', 'StickerController@uploadImage');

#Edit sticker
Route::get('/sticker/{id}/edit', 'StickerController@edit');
Route::post('/sticker/{id}/edit', 'StickerController@update');

#Delete sticker
Route::post('/delete/{id}', 'StickerController@destroy');

#Delete image
Route::get('/stickers/deleteImage/{id}', 'StickerController@deleteImage');

#Delete selected images
Route::delete('/delete/images', 'StickerController@deleteImages');

#Sticker
Route::get('/sticker/{id}', 'StickerController@show');
Route::get('/category/{base_slug}/{slug}', 'HomeController@stickersWithSubCategorySlug');
Route::get('/city/{slug}', 'HomeController@stickersWithCitySlug');

#My stickers
Route::get('/my-stickers', 'StickerController@myStickers');

#Favourite Stickers
Route::get('/favourite-stickers', 'StickerController@favourites');


#Auth
Route::get('logout', 'Auth\LoginController@logout');


Auth::routes();

app/Sticker.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sticker extends Model

{
    protected $fillable = [
      'name',
      'city_id',
      'description',
      'img',
      'author_name',
      'author_email',
      'phone',
      'price',
      'new',
      'user_id',
      'sub_category_id',
      'status',
    ];


    public function city(){
      return $this->belongsTo('App\City');
    }

    public function user(){
      return $this->belongsTo('App\User');
    }

    public function sub_category(){
      return $this->belongsTo('App\SubCategory');
    }

    public function images(){
      return $this->hasMany('App\StickerImage', 'sticker_id');
    }

    public function wishlist(){
     return $this->hasMany(Wishlist::class);
    }


}

app/Http/Controllers/StickerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Cache;
use Session;
use Illuminate\Http\Request;
use App\Category;
use App\City;
use App\SubCategory;
use App\Sticker;
use App\StickerImage;
use Auth;
use Validator;
use File;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;

class StickerController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    //
  }

  public function stickers(Request $request)
  {
    $_stickers = Sticker::where('status', 1);

    if(request()->get('sort')){
      if(request()->get('sort') == 0){
        $_stickers->orderBy('id','desc');
      }elseif(request()->get('sort') == 1){
        $_stickers->orderBy('price', 'asc');
      }elseif(request()->get('sort') == 2){
        $_stickers->orderBy('price', 'desc');
      }

      $stickers = $_stickers->with('city')->paginate(8);
      $stickers->appends(request()->query());

    }else{
      $_stickers->orderBy('id','desc');
      $stickers = $_stickers->with('city')->paginate(8);
    }

    if($request->ajax()){

      return view('site.stickers.ajax.sticker',compact('stickers'));

    }else{
      return view('site.stickers.stickers',compact('stickers'));
    }

  }



  public function myStickers(Request $request){
    $stickers = Sticker::where('user_id', Auth::user()->id)
    ->where('status', 1)
    ->orWhere('status', 2)
    ->where('user_id', Auth::user()->id);

    if(request()->get('sort')){
      if(request()->get('sort') == 0){
        $stickers->orderBy('id','desc');
      }elseif(request()->get('sort') == 1){
        $stickers->orderBy('price', 'asc');
      }elseif(request()->get('sort') == 2){
        $stickers->orderBy('price', 'desc');
      }

      $stickers = $stickers->paginate(8);
      $stickers->appends(request()->query());

    }else{
      $stickers->orderBy('id','desc');
      $stickers = $stickers->paginate(8);
    }

    if($request->ajax()){
      return view('site.stickers.ajax.sticker',compact('stickers'));
    }else{
      return view('site.profile.my-stickers', compact('stickers'));
    }

  }




  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $categories = Cache::remember('categories', 86400, function () {
      return Category::select('id','name')->get();
    });

    $cities = Cache::remember('cities', 86400, function () {
      return City::select('id','name','slug')->get();
    });

    return view('site.stickers.addSticker', compact('categories','cities'));
  }

  public function subCategory($id){
    $sub_categories = SubCategory::where('category_id', $id)->get();
    return response()->json($sub_categories);
  }



  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    //Validation
    $validator = Validator::make($request->all(), [
      'name' => 'required|min:2|max:255',
      'sub_category_id' => 'required',
      'category' => 'required',
      'city_id'=> 'required',
      'description'=> 'required|min:2',
      'author_name'=> 'required',
      'author_email'=> 'required|email',
      'phone'=> 'required|numeric',
      'price'=> 'required|numeric',
    ],
    [
      'name.required' => 'Elanın adını daxil edin',
      'name.min' => 'Elanın adı minimum 2 simvol ola bilər',
      'name.max' => 'Elanın adı maksimum 255 simvol ola bilər',
      'category.required' => 'Kateqoriyanı daxil edin',
      'sub_category_id.required' => 'Alt kateqoriyanı daxil edin',
      'city_id.required' => 'Şəhəri daxil edin',
      'description.required' => 'Məzmun boş ola bilməz',
      'description.min' => 'Məzmun minimum 2 simvol ola bilər',
      'author_name.required' => 'Müəllif boş ola bilməz',
      'author_email.required' => 'Email boş ola bilməz',
      'author_email.unique' => 'Email artıq istifadə olunub',
      'author_email.email' => 'Emaili düzgün daxil edin',
      'phone.required' => 'Mobil nömrəni daxil edin',
      'phone.numeric' => 'Mobil nömrəni düzgün daxil edin',
      'price.required' => 'Qiyməti daxil edin',
      'price.numeric' => 'Qiyməti düzgün daxil edin',
    ]
  );

  if($validator->fails()){
    $errors = $validator->errors();
    return response()->json(['message' => $errors]);
  }


  //Check auth
  if(Auth::check()){
    $user_id = Auth::user()->id;
  }else{
    $user_id = NULL;
  }

  $sticker = Sticker::create([
    'name'=>$request->name,
    'sub_category_id'=>$request->sub_category_id,
    'city_id'=>$request->city_id,
    'description'=>strip_tags($request->description),
    'author_name'=>$request->author_name,
    'author_email'=>$request->author_email,
    'phone'=>$request->phone,
    'price'=>$request->price,
    'new'=>$request->new ? 1 : 0 ?? 0,
    'status'=>2,
    'user_id' => $user_id
  ]);

  if($sticker){
    #Insert image
    for ($i=0; $i < count($request->photos); $i++) {
      StickerImage::create([
        'sticker_id' => $sticker->id,
        'file_name' => $request->photos[$i]
      ]);
    }

    Cache::forget('stickers');
    Cache::forget('cities');
    return response()->json(['message' => "success"]);
  }else{
    return response()->json(['message' => "error"]);
  }

}


/*
* Add Image
*/

public function uploadImage(Request $request){

  $validator = Validator::make($request->all(), [
    'file' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:4096'
  ]);

  if ($validator->fails()) {
    return response()->json([
      'message' => 'Error'
    ], 400);
  }

  $photos = $request->file('file');

  if (!is_array($photos)) {
    $photos = [$photos];
  }

  for ($i = 0; $i < count($photos); $i++) {
    $photo = $photos[$i];
    $name = sha1(date('YmdHis') . str_random(30));
    $filename = $name . '.' . $photo->getClientOriginalExtension();
    $directory = 'images';
    $full_filename = "$directory/$filename";
    $path = public_path($full_filename);

    Image::make($photo->getRealPath())->fit(310,277)->save($path);

    return response()->json([
      'file_name'=>$full_filename
    ]);
  }

  return response()->json([
    'message' => ['success']
  ], 200);

}


/**
* Display the specified resource.
*
* @param  int  $id
* @return \Illuminate\Http\Response
*/
public function show($id)
{
  $sticker = Sticker::where('id', $id)
  ->where('status', 1)
  ->orWhere('status', 2)
  ->where('id', $id)
  ->firstOrFail();
  return view('site.stickers.sticker-detail', compact('sticker'));
}




/**
* Show the form for editing the specified resource.
*
* @param  int  $id
* @return \Illuminate\Http\Response
*/
public function edit($id)
{

  //Check auth
  if(Auth::check()){
    $user_id = Auth::user()->id;
  }else{
    abort(404);
  }

  $sticker = Sticker::where('id',$id)->where('user_id',$user_id)->firstOrFail();

  $categories = Cache::remember('categories', 86400, function () {
    return Category::select('id','name')->get();
  });

  $cities = Cache::remember('cities', 86400, function () {
    return City::select('id','name','slug')->get();
  });

  return view('site.stickers.editSticker', compact('categories','cities','sticker'));
}

/**
* Update the specified resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @param  int  $id
* @return \Illuminate\Http\Response
*/
public function update(Request $request, $id)
{
  $sticker = Sticker::findOrFail($id);
  //Validation
  $validator = Validator::make($request->all(), [
    'name' => 'required|min:2|max:255',
    'sub_category_id' => 'required',
    'category' => 'required',
    'city_id'=> 'required',
    'description'=> 'required|min:2',
    'author_name'=> 'required',
    'author_email'=> 'required|email',
    'phone'=> 'required|numeric',
    'price'=> 'required|numeric',
  ],
  [
    'name.required' => 'Elanın adını daxil edin',
    'name.min' => 'Elanın adı minimum 2 simvol ola bilər',
    'name.max' => 'Elanın adı maksimum 255 simvol ola bilər',
    'category.required' => 'Kateqoriyanı daxil edin',
    'sub_category_id.required' => 'Alt kateqoriyanı daxil edin',
    'city_id.required' => 'Şəhəri daxil edin',
    'description.required' => 'Məzmun boş ola bilməz',
    'description.min' => 'Məzmun minimum 2 simvol ola bilər',
    'author_name.required' => 'Müəllif boş ola bilməz',
    'author_email.required' => 'Email boş ola bilməz',
    'author_email.unique' => 'Email artıq istifadə olunub',
    'author_email.email' => 'Emaili düzgün daxil edin',
    'phone.required' => 'Mobil nömrəni daxil edin',
    'phone.numeric' => 'Mobil nömrəni düzgün daxil edin',
    'price.required' => 'Qiyməti daxil edin',
    'price.numeric' => 'Qiyməti düzgün daxil edin',
  ]
);

if($validator->fails()){
  $errors = $validator->errors();
  return response()->json(['message' => $errors]);
}


#Update sticker
$edit = Sticker::where('id', $id)->update([
  'name'=>$request->name,
  'sub_category_id'=>$request->sub_category_id,
  'city_id'=>$request->city_id,
  'description'=>$request->description,
  'author_name'=>$request->author_name,
  'author_email'=>$request->author_email,
  'phone'=>$request->phone,
  'price'=>$request->price,
  'new'=>$request->new ? 1 : 0 ?? 0,
  'status'=>1,
  'user_id' => Auth::user()->id
]);


if($edit){
    #Insert image
    if($request->photos){
      for ($i=0; $i < count($request->photos); $i++) {
        StickerImage::create([
          'sticker_id' => $sticker->id,
          'file_name' => $request->photos[$i]
        ]);
      }
    }
    Cache::forget('stickers');
    Cache::forget('cities');
    return response()->json(['message' => "success"]);
  }else{
    return response()->json(['message' => "error"]);
  }

}

/**
* Remove the specified resource from storage.
*
* @param  int  $id
* @return \Illuminate\Http\Response
*/
public function destroy($id)
{

  if(Auth::check()){

resources/views/site/stickers/addSticker.blade.php
@extends('site.layouts.app')
  @section('css')
    <link rel="stylesheet" type="text/css"  href="{{ asset('css/dropzone.css') }}">
  @endsection
@section('content')
  <!--inner heading start-->
  <div class="inner-heading">
    <div class="container">
      <h1>Yeni elan</h1>
    </div>
  </div>
  <!--inner heading end-->

  <!--ad post start-->
  <div class="inner-wrap listing">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-2"></div>
        <div class="col-md-6 col-sm-8">
          <div class="login">
            <div class="contctxt">İnformasiyaları əlavə edin</div>
            <div id="errorResponse">

            </div>
            <div class="formint conForm">
              <form class="form-group" action="" id="addSticker" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <select class="form-control" name="category" id="category">
                        <option value="">Kateqoriyalar</option>
                        <?php foreach ($categories as $key => $category): ?>
                          <option value="{{ $category->id }}">{{ $category->name }}</option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <select class="form-control" name="sub_category_id" id="sub_category">
                        <option value="">Alt Kateqoriyalar</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="input-wrap">
                  <input type="text" name="name" class="form-control" placeholder="Elanın adı">
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <input type="text" name="price" placeholder="Qiymət" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-wrap row">
                      <label for="checkbox" class="col-md-6"><h3>Yeni</h3></label>
                      <input type="checkbox" name="new" id="checkbox" class="form-control col-md-6">
                    </div>
                  </div>
                </div>
                <div class="input-wrap">
                  <textarea name="description" rows="5" cols="80" class="form-control" placeholder="Məzmun"></textarea>
                </div>
                <div class="input-wrap">
                  <div id="myDropZone" class="dropzone dropzone-design">
                    <div class="dz-default dz-message"><span>Şəkilləri bura yerləşdirin</span></div>
                  </div>
                  <div id="productImages"></div>
                </div>

                <div class="contctxt persional">Şəxsi İnformasiyalar</div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <input type="text" name="author_name" class="form-control"
                      value="{{ (Auth::check()) ? Auth::user()->name : '' }}" placeholder="Adınız">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <input type="text" name="author_email" class="form-control"
                      value="{{ (Auth::check()) ? Auth::user()->email : '' }}" placeholder="Emailiniz">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <input type="text" name="phone" placeholder="Mobil nömrə" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-wrap">
                      <select class="form-control" name="city_id">
                        <option value="">Şəhər seçin</option>
                        <?php foreach ($cities as $key => $city): ?>
                          <option value="{{ $city->id }}">{{ $city->name }}</option>
                        <?php endforeach; ?>
                      </select>
                  </div>
                </div>
                <div class="sub-btn">
                  <button type="submit" id="addSticker_submit" class="sbutn">Əlavə et</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-2"></div>
      </div>
    </div>
  </div>
  <!--ad post end-->


@endsection

@section('js')
  <script type="text/javascript" src="{{ asset('/js/dropzone.js') }}"></script>
  <script>

  Dropzone.autoDiscover = false;

  $(function () {
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $("div#myDropZone").dropzone({
      url: "{{ url('/sticker/addImage') }}",
      sending: function(file, xhr, formData) {
        formData.append("_token", CSRF_TOKEN);
      },
      success:function(re){
        var obj = $.parseJSON(re.xhr.response);
        $("#productImages").append('<input type="hidden" value="'+ obj.file_name +'" name="photos[]"/>');
      }
    });
  });

  $("#category").change(function(){
    $("#sub_category").empty();
    $.ajax({
      type: 'GET',
      url: '{{ url('/sticker/add/getSubCategory') }}/'+$(this).val(),
      dataType: 'json',
      success: function (data) {
        $.each(data, function(index, element) {
          $('#sub_category').append('"<option value="'+element.id+'">' + element.name +'</option>');
        });
      }
    });
  });


  $("#addSticker").submit(function(){
    $("#addSticker_submit").text("Əlavə edilir...").css('opacity','0.6');
    $.ajax({
      url:"{{url('/sticker/add')}}",
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      method:"POST",
      data:$(this).serialize(),
      success: function(response){
        $('html, body').animate({scrollTop:$('#errorResponse').offset().top}, 'slow');
        if(response.message == "success"){
          if ($(".alert")[0]){
            $("#errorResponse").removeClass();
          }
          $("#errorResponse").empty().html('<div class="alert alert-success">Əlavə edildi</div>');
          $(".form-control").val("");
          $("#checkbox").prop("checked", false);
          Dropzone.forElement('#myDropZone').removeAllFiles(true)
        }else{
          $("#errorResponse").empty();
          $("#errorResponse").addClass('alert alert-danger');
          $.each(response.message, function( k, v ) {
              $("#errorResponse").append('<span>'+v+'</span><br>');
            });
        }
        $("#addSticker_submit").text("Əlavə et").css('opacity','1');
      },
      error: function(response){
        $("#errorResponse").empty().html('<div class="alert alert-danger">Səhv baş verdi</div>');
        $("#addSticker_submit").text("Əlavə et").css('opacity','1');
      }
    });

    return false;
  });
</script>
@endsection

resources/views/site/stickers/sticker-detail.blade.php
@extends('site.layouts.app')
@section('css')
  <link href="{{ asset('backend/css/sweet-alert.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('frontend/classified/css/flexslider.css')}}" type="text/css" media="screen" />
@endsection
@section('content')

  <!--inner heading start-->
  <div class="inner-heading">
    <div class="container">
      <h1>{{$sticker->name}}</h1>
    </div>
  </div>
  <!--inner heading end-->

  <!--Detail page start-->
  <div class="inner-wrap about">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div id="main" role="main">
            <div class="slider">
              <div class="flexslider innerslider">
                <ul class="slides">
                  @foreach ($sticker->images as $image)
                    <li data-thumb="{{ asset($image->file_name) }}"> <img src="{{ asset($image->file_name) }}" alt="img"/> </li>
                  @endforeach
                </ul>
              </div>
            </div>
          </div>
          <h2>Təsvir</h2>
          <p>{!!$sticker->description!!}</p>

        </div>
        <div class="col-md-4">
          @if ($sticker->status == 1)
            <div class="sidebarWrp">
              <div class="userinfo">
                <div class="icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                <h3>{{$sticker->author_name}}</h3>
              </div>
              <div class="innerprice">{{$sticker->price}} Azn</div>
              <div class="phone">{{ $sticker->phone }}</div>
            </div>
            <div class="safety-tips">
              <ul class="featureLinks">
                <li>Şəhər <span class="right">{{$sticker->city->name}}</span></li>
                <li>Kateqoriya <span class="right">{{$sticker->sub_category->category->name}}</span></li>
                <li> Yeni<span class="right">{{ ($sticker->new == 1) ? 'Bəli' : 'Xeyr'}}</span></li>
              </ul>
            </div>
            <br>
            <div class="row">
              @if(Auth::check() && Auth::user()->id == $sticker->user_id)
                <div class="col-md-3">
                  <a href="{{ url('/sticker').'/'.$sticker->id.'/edit' }}" class="btn btn-warning">Düzəliş et</a>
                </div>
                <div class="col-md-3">
                  <form class="form-group" id='data-item-form{{$sticker->id}}' action="{{ url('/delete').'/'.$sticker->id }}" method="post">
                    @csrf
                    <a href="javascript:void(0)" onclick="removeItem({{ $sticker->id }})" class="btn btn-danger">Sil</a>
                  </form>
                </div>
                <div class="col-md-6">
                  <?php
                  $wishlist = App\Wishlist::where('user_id', Auth::user()->id)
                  ->where('sticker_id',$sticker->id)->first();
                  ?>
                  <form action="{{route('wishlist.store')}}" id="wishlist_form" method="post">
                    {{csrf_field()}}
                    <input name="user_id" type="hidden" value="{{Auth::user()->id}}" />
                    <input name="sticker_id" type="hidden" value="{{$sticker->id}}" />
                    <button type="submit" id="wishlist" class="form-control">
                      @if($wishlist) Seçilmişlərdən çıxart @else Seçilmişlərə əlavə et @endif
                    </button>
                  </form>
                </div>
                <div class="col-md-12">
                    <div id="wishlistResponse">

                    </div>

                </div>
              @endif
            </div>
          @else
            <h3 class="alert alert-danger">Elan aktiv deyil</h3>
          @endif

        </div>
      </div>
    </div>
  </div>
  <!--Detail page end-->
@endsection
@section('js')
  <script src="{{ asset('backend/js/sweet-alert.js') }}"></script>
  <script>
  function removeItem($id) {

    swal({
      title: "Are you sure",
      text: "You will be able to recover this data!",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Yes, sure",
      cancelButtonText: "No, cancel",
      allowOutsideClick: true,
    },
    function (isConfirm) {
      if (isConfirm) {
        $('#data-item-form' + $id).submit();
      }
    });
  }

  $("#wishlist_form").submit(function(){

    $.ajax({
      url: '{{route('wishlist.store')}}',
      dataType: 'json',
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      method:"POST",
      data:$(this).serialize(),
      success: function (data) {
        if(data=='added'){
          $("#wishlistResponse").empty().html('<div class="alert alert-success">Elan seçilmişlərə əlavə olundu</div>');
          $("#wishlist").text("Seçilmişlərdən çıxart");
        }else{
          $("#wishlistResponse").empty().html('<div class="alert alert-success">Elan seçilmişlərdən silindi</div>');
          $("#wishlist").text("Seçilmişlərə əlavə et");
        }
      }
    });
    return false;
  });


  </script>
  <script defer src="{{ asset('frontend/classified/js/jquery.flexslider.js') }}"></script>
  <script type="text/javascript">
  $(window).load(function(){
    $('.flexslider').flexslider({
      animation: "slide",
      controlNav: "thumbnails",
      start: function(slider){
        $('body').removeClass('loading');
      }
    });
  });
  </script>
@endsection